#!/usr/bin/env python

import click
import re
import os
from pathlib import Path

date_prefix_pattern = re.compile(
    r"^\d{4}(-\d{2}){0,2}"
)  # Matches YYYY- or YYYY-MM- or YYYY-MM-DD-


def add_from_filename(pdf_filenames: set, filepath: Path):
    clean_name = date_prefix_pattern.sub("", filepath.stem)
    pdf_filenames.add(clean_name)


def scantree(pdf_filenames: set, path):
    with os.scandir(path) as it:
        for entry in it:
            if entry.is_dir():
                # print(repr(entry))
                scantree(pdf_filenames, entry.path)  # Recursively walk subdirectories
            elif entry.is_file():
                filepath = Path(entry)
                # print(repr(filepath))
                if filepath.suffix == ".pdf":
                    add_from_filename(pdf_filenames, filepath)


@click.command()
@click.option("--source-file")
@click.option("--destination-directory", default=".")
def get_unique_pdf_suffixes(source_file, destination_directory) -> list[str]:
    pdf_filenames = set()
    add_from_filename(pdf_filenames, Path(source_file))
    scantree(pdf_filenames, destination_directory)
    for name in sorted(pdf_filenames):
        print(name)


if __name__ == "__main__":
    unique_filenames = get_unique_pdf_suffixes()
