#!/usr/bin/env python

import click
import os
import re


@click.command()
@click.option("--source-file")
@click.option("--destination-directory", default=".")
def get_unique_pdf_suffixes(source_file, destination_directory) -> list[str]:
    pdf_filenames = set()
    date_prefix_pattern = re.compile(
        r"^\d{4}(-\d{2}){0,2}-"
    )  # Matches YYYY- or YYYY-MM- or YYYY-MM-DD-

    # for filename in os.listdir(destination_directory) + [source_file]:
    for filename in os.listdir(destination_directory):
        if filename.endswith(".pdf"):
            clean_name = date_prefix_pattern.sub("", filename)  # Remove the date prefix
            clean_name = os.path.splitext(clean_name)[0]  # Remove .pdf extension
            pdf_filenames.add(clean_name)

    for name in sorted(pdf_filenames):
        print(name)


if __name__ == "__main__":
    unique_filenames = get_unique_pdf_suffixes()
